apiVersion: v1
kind: Service
metadata:
  name: owncast
  namespace: owncast
  labels:
    app: owncast
spec:
  selector:
    app: owncast
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
    - name: rtmp
      port: 1935
      targetPort: rtmp
      protocol: TCP
  type: ClusterIP