apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: traefik-middleware
  namespace: flux-system
spec:
  interval: 5m
  path: ../../infrastructure/traefik/middleware
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn: 
    - name: traefik